### ISSUE TITLE
Task List for recode:

### ISSUE THREAD

**Issue by p410n3** [p410n3/YDL-UI#12]
Over the time I have had many Ideas to further improve this project and consider re-coding it from scratch. As of now, many people like it but few have it actually set it up from what I gathered. But they rather requested me or someone else to give them access to an already installed version. 

So heres a tasklist:

- [ ] Add SQLite to maintain portability but also have all the advantages of a real database.
- [ ] Privilged admin account(s)
- [ ] PHP Cron job to delete stuff instead of the current way. 
- [ ] Limit Space to not flood the server
- [ ] Remove Password protection when the admin wants to.
- [ ] Change configurations via a backend type Interface
- [ ] Invite links for Users instead of manually entering them
- [ ] Install routine including youtube-dl and ffmpeg. Due to required root Permissions, most likely an shell script.
- [ ] Checking PHP for compatibility issues e.g. missingSQLite extension.

Possibly, I will also use that chance and use Laravel instead of RAW PHP. 

I will take some time to get even started due to personal lack of free time, maybe I wont even start until mid 2019, but I am making this list just now So I can add stuff until I am able to start.

Comment here if you have some Ideas yourself and I might add them If I find them to be good.

**Comment by zstima** [comment]
do u accept pull requests ? any rules ?

i have time on my hands and would like to participe because i wanted to make this a while back and i just got this singular g-mail about this project.

**Comment by zstima** [comment]
On another note, i can quickly make your project into a fully blown (or mildly blown)
laravel/cake/phalcon/yii2/symfony project

**Comment by p410n3** [comment]
> do u accept pull requests ? any rules ?
> 
> i have time on my hands and would like to participe because i wanted to make this a while back and i just got this singular g-mail about this project.

Do whatever you want. Its using the "unlicense" for a reason. For all I care you can recode that in RISC-V assembler. Just... dont hide malware or anything malicious obviously

> On another note, i can quickly make your project into a fully blown (or mildly blown)
> laravel/cake/phalcon/yii2/symfony project

Sounds amazing! My current code is kind of emberassing I have to say (goes to show how much I learned since then). Any help is appreciated. Make it yours. Have fun while doing it!

Peace

PS: How did you get a email about this btw?
